### ISSUE TITLE
Unable to get the Maui Android Sample to Work

### ISSUE THREAD

**Issue by appsure** [rdavisau/tbc#5]
Will there be support soon?

**Comment by rdavisau** [comment]
I've updated the sample to work with android; you can see the changes I made [here](https://github.com/rdavisau/tbc/commit/0dcbb531a4c2ff06b053b1a89a72337bf2c2420b). And I recorded a [quick video](https://rdavisau.blob.core.windows.net/zzz/tbc-maui-android.mp4?sv=2020-08-04&st=2023-02-08T02%3A25%3A12Z&se=2050-02-09T02%3A25%3A00Z&sr=b&sp=r&sig=oRvblPXgJWBa6qNsMO8n%2FpCGrzTS6MpLuPccEslx6z0%3D) showing it.

Per the video you need to use adb to forward the listening port from android device to localhost (in the sample case, it's `50130`). On android, you also have to wait some time for the app to send its dependencies back to the host (on iOS, the host can just read them off disk). I've considered a caching feature for this but I usually spend most of my time on iOS so have not prioritised it yet. 

Let me know how you go.

**Comment by appsure** [comment]
This looks great, I'll test it out in the morning here EST.  Thank you for putting this together, I've been looking for this for a while!

**Comment by appsure** [comment]
Confirmed Android works, just the ability to cache assemblies would make this even better!  It's not too bad once it loads up...takes about 15sec on my machine/solution.  Thanks again!

**Comment by rdavisau** [comment]
Awesome. I will take another look at the caching option 🙂
